### ISSUE TITLE
make fails for python in docker

### ISSUE THREAD

**Issue by BeamupAI** [CGAL/cgal-swig-bindings#121]
Hey,

I'm trying to compile CGAL with python binding on docker.

Im using the default docker python:3 image.

Installed all dependencies: 

apt-get -y install vim apt-utils cmake libboost-all-dev libgmp3-dev libmpfr-dev libeigen3-dev libcgal-dev swig

followed installation example and changed cmake to:

cmake -DCGAL_DIR=/usr/lib/CGAL -DBUILD_JAVA=OFF -DBUILD_PYTHON=ON -DPYTHON_OUTDIR_PREFIX=../../examples/python ../..

running make fails at:

Scanning dependencies of target CGAL_Mesh_3_cpp
[ 62%] Building CXX object SWIG_CGAL/Mesh_3/CMakeFiles/CGAL_Mesh_3_cpp.dir/Object.cpp.o
[ 63%] Linking CXX shared library ../../lib/libCGAL_Mesh_3_cpp.so
[ 63%] Built target CGAL_Mesh_3_cpp
[ 64%] Building CXX object SWIG_CGAL/Mesh_3/CMakeFiles/_CGAL_Mesh_3_python.dir/__/__/examples/python/CGAL/CGAL_Mesh_3PYTHON_wrap.cxx.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
SWIG_CGAL/Mesh_3/CMakeFiles/_CGAL_Mesh_3_python.dir/build.make:70: recipe for target 'SWIG_CGAL/Mesh_3/CMakeFiles/_CGAL_Mesh_3_python.dir/__/__/examples/python/CGAL/CGAL_Mesh_3PYTHON_wrap.cxx.o' failed
make[2]: *** [SWIG_CGAL/Mesh_3/CMakeFiles/_CGAL_Mesh_3_python.dir/__/__/examples/python/CGAL/CGAL_Mesh_3PYTHON_wrap.cxx.o] Error 4
CMakeFiles/Makefile2:854: recipe for target 'SWIG_CGAL/Mesh_3/CMakeFiles/_CGAL_Mesh_3_python.dir/all' failed
make[1]: *** [SWIG_CGAL/Mesh_3/CMakeFiles/_CGAL_Mesh_3_python.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

What am I missing?

**Comment by lrineau** [comment]
You probably did not have enough memory. Try to extend the quantity of RAM available for Docker.

**Comment by BeamupAI** [comment]
Thanks @lrineau. Extending RAM to 6GB did the trick.. 
Can you tell if everything installing is required? The image turns out to be almost 2GB..

Thanks

**Comment by lrineau** [comment]
A few suggestions:
 - `libgmp3-dev` and `libmpfr-dev` are already pulled by `libcgal-dev`. You can remove them from the `apt` command line (but it will not change anything).
- You can probably be more parsimonious with Boost: instead of installing `libboost-all-dev`, remove it from the command line, and let `apt` install the dependencies of `libcgal-dev`.
- Keep installing `libeigen3-dev`, because it is required by a lot of modules of CGAL.

**Comment by twneale** [comment]
@BeamupAI Did this end up working? Is CGAL swig working with Python3 now? Docs indicate it has only been tested with 2.7 (which is reaching end-of-life in January 2020).
