### ISSUE TITLE
cgal-swig-bindings 'master' does not compile with CGAL 'master'

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-swig-bindings#124]
See 
- https://travis-ci.org/CGAL/cgal-swig-bindings/builds/531652561
- https://travis-ci.org/CGAL/cgal-swig-bindings/builds/531705836

@maxGimeno can you have a look at that issue? I wonder what we broke in CGAL-5.0-dev.

**Comment by sloriot** [comment]
Closing this issue, it builds correctly with master.
