### ISSUE TITLE
Support for CGAL::orientation()

### ISSUE THREAD

**Issue by rteshnizi** [CGAL/cgal-swig-bindings#128]
There are several functions in the CGAL Kernel that are very handy for quick checks:
* [CGAL::collinear()](https://doc.cgal.org/latest/Kernel_23/group__collinear__grp.html)
* [CGAL::left_turn()](https://doc.cgal.org/latest/Kernel_23/group__left__turn__grp.html)
* [CGAL::right_turn()](https://doc.cgal.org/latest/Kernel_23/group__right__turn__grp.html)
* [CGAL::orientation()](https://doc.cgal.org/latest/Kernel_23/group__orientation__grp.html)

From all these I think orientation() is the most versatile as it can serve the purpose for the other three. Is it possible to add support for that function?

**Comment by sloriot** [comment]
Fixed by c8c7a53

**Comment by rteshnizi** [comment]
Thanks for adding this. Please don't forget to update your [wiki page](https://github.com/CGAL/cgal-swig-bindings/wiki/KernelPrimitives)
