### ISSUE TITLE
Missing bindings for Shape_detection_3

### ISSUE THREAD

**Issue by thopiekar** [CGAL/cgal-swig-bindings#131]
Hello everybody,

are there any plans or even work in progress around for Shape_detection_3 bindings?
Would be glad to use these bindings here to process some point clouds.

Thanks!

**Comment by lrineau** [comment]
@sgiraudot, is that the bindings you were working on?

**Comment by thopiekar** [comment]
@lrineau Do you think @sgiraudot or you could find some time and review #138 ? :smile:
