### ISSUE TITLE
missing setup.py

### ISSUE THREAD

**Issue by T4mmi** [CGAL/cgal-swig-bindings#142]
Hi all,

Thanks for the bindings, this is a GREAT help for fast prototyping and interfacing with *python-enabled* softwares *(wink paraview)* …

I was looking at the wiki about [custom packages](https://github.com/CGAL/cgal-swig-bindings/wiki/User_package) to include extended/non-yet-wrapped features *(like vtu export of mesh)*, when I realized that there is no `setup.py` file provided in this project.  
I think that would be a great help to allow *simple* build/distribution of the forked/customed CGAL bindings *(i.e. avoid building and manual installation with a basic `pip install .`)*

Is it on purpose or am I missing something ?

**Comment by sloriot** [comment]
I guess the current installation procedure could be also applied to the custom packages. I think everything is done at the cmake level currently.

**Comment by T4mmi** [comment]
Yeah I guess so, I was just wondering if there was a more *user-friendly* way to do it … and to manage virtual envs easily ;)

**Comment by maxGimeno** [comment]
Fixed by #162
