### ISSUE TITLE
Error in Interpolation input_iterator_wrappers

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal-swig-bindings#143]
Assertion failure here : 
https://travis-ci.org/CGAL/cgal-swig-bindings/jobs/623143387#L4781

The iterator_wrapper needs to be forward, but it is currently single_pass.

Note:  Replacing the flag in the definition leads to an infinite loop in Triangulation_2.

**Comment by sloriot** [comment]
Fixed in #141
