### ISSUE TITLE
[Todo] Create a pip package

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal-swig-bindings#147]
At some point, we'd like the users of the Python bindings to be able to just use `pip install cgal` and get it installed right away. This issue is for centralizing discussions and resources on that topic.
- issue https://github.com/CGAL/cgal-swig-bindings/issues/142 mentions the need for a `setup.py` file
- PR https://github.com/CGAL/cgal-swig-bindings/pull/100 is a submission for such `setup.py`, but it is quite old and probably outdated
- a package [cgal-bindings](https://pypi.org/project/cgal-bindings/) exists (related to the previous PR if I'm not mistaken) but has not been updated in 2 years. I've tried running `pip install cgal-bindings` and I got an error `You are missing the CGAL library`.

The main question is: how do we handle dependencies? If we let it up to users to install CGAL on their side (as it seems to be done with the existing package), then the install procedure becomes as complicated as for the C++ version, which is probably a bad idea as Python users will want to do `pip install cgal` and get started right away.

@afabri pointed to me some [documentation about packaging binary extensions](https://packaging.python.org/guides/packaging-binary-extensions/#building-binary-extensions) which seem to be a good starting point (provided precompiled binaries for each system inside the pip package), as it seems complicated to expect CGAL to be rebuilt from scratch when the pip package is installed.

**Comment by lrineau** [comment]
I would like to share a few links I bookmarked during a brief research on that topic, a few weeks ago:
- [Extending setuptools extension to use CMake in setup.py (in StackOverflow)](https://stackoverflow.com/a/48015772/1728537)
- [Building a Python C extension module with CMake (a blog post)](https://martinopilia.com/posts/2018/09/15/building-python-extension.html)
- [cibuildwheel: a tool to automatically build Python binary packages (wheels) for several platforms, using Travis or Github Actions](https://github.com/joerick/cibuildwheel)

**Comment by sgiraudot** [comment]
Wheels seems to be a good option indeed: https://pip.pypa.io/en/stable/reference/pip_wheel/

**Comment by sgiraudot** [comment]
[Building a PyPI Package for a Modern C++ Project ](https://thomastrapp.com/blog/building-a-pypi-package-for-a-modern-cpp-project/), a quiet extensive tutorial in which the Python module is built with SWIG.

**Comment by lrineau** [comment]
> [Building a PyPI Package for a Modern C++ Project ](https://thomastrapp.com/blog/building-a-pypi-package-for-a-modern-cpp-project/), a quite extensive tutorial in which the Python module is built with SWIG.

This blog post has major flaw: its `setup.py` does not compile the binary modules, but assumes they are already precompiled in the sources directory.

**Comment by afabri** [comment]
If it must be precompiled by the provider of the python package I do not consider it as a flaw.    The python developer will not necessarily have VC++.

**Comment by maxGimeno** [comment]
I don't see us shipping the sources of every dependency of ours, with a magic formula to be able to build it on any platform either.

**Comment by maxGimeno** [comment]
Fixed by #162
