### ISSUE TITLE
error: ‘Region_growing’ in namespace ‘CGAL::Shape_detection_3’ does not name a template type

### ISSUE THREAD

**Issue by thopiekar** [CGAL/cgal-swig-bindings#150]
Hey!

I've got some trouble building the bindings on Ubuntu. As mentioned in the main repository, I'm trying to build Debian packages for Ubuntu on launchpad.net.
However, after I've upgraded the CGAL packages, I end up with the following error:
```
Scanning dependencies of target CGAL_Shape_detection_3_python
make[4]: Leaving directory '/<<PKGBUILDDIR>>/build-python3.7'
make[4]: Entering directory '/<<PKGBUILDDIR>>/build-python3.7'
[ 46%] Building CXX object SWIG_CGAL/User_packages/Shape_detection_3/CMakeFiles/CGAL_Shape_detection_3_python.dir/__/__/__/build-python/CGAL/CGAL_Shape_detection_3PYTHON_wrap.cxx.o
In file included from /usr/include/CGAL/Shape_detection/deprecated/Region_growing.h:48,
                 from /usr/include/CGAL/Shape_detection_3.h:22,
                 from /<<PKGBUILDDIR>>/SWIG_CGAL/User_packages/Shape_detection_3/Shape_detection_3.h:23,
                 from /<<PKGBUILDDIR>>/SWIG_CGAL/User_packages/Shape_detection_3/all_includes.h:12,
                 from /<<PKGBUILDDIR>>/build-python3.7/build-python/CGAL/CGAL_Shape_detection_3PYTHON_wrap.cxx:3144:
/usr/include/CGAL/internal/deprecation_warning.h:80:6: warning: #warning "A deprecated header has been included." [-Wcpp]
   80 | #    warning "A deprecated header has been included."
      |      ^~~~~~~
In file included from /usr/include/CGAL/Shape_detection/deprecated/Shape_detection_traits.h:30,
                 from /usr/include/CGAL/Shape_detection_3.h:23,
                 from /<<PKGBUILDDIR>>/SWIG_CGAL/User_packages/Shape_detection_3/Shape_detection_3.h:23,
                 from /<<PKGBUILDDIR>>/SWIG_CGAL/User_packages/Shape_detection_3/all_includes.h:12,
                 from /<<PKGBUILDDIR>>/build-python3.7/build-python/CGAL/CGAL_Shape_detection_3PYTHON_wrap.cxx:3144:
/usr/include/CGAL/internal/deprecation_warning.h:80:6: warning: #warning "A deprecated header has been included." [-Wcpp]
   80 | #    warning "A deprecated header has been included."
      |      ^~~~~~~
In file included from /usr/include/CGAL/Shape_detection_3.h:29,
                 from /<<PKGBUILDDIR>>/SWIG_CGAL/User_packages/Shape_detection_3/Shape_detection_3.h:23,
                 from /<<PKGBUILDDIR>>/SWIG_CGAL/User_packages/Shape_detection_3/all_includes.h:12,
                 from /<<PKGBUILDDIR>>/build-python3.7/build-python/CGAL/CGAL_Shape_detection_3PYTHON_wrap.cxx:3144:
/usr/include/CGAL/internal/deprecation_warning.h:80:6: warning: #warning "A deprecated header has been included." [-Wcpp]
   80 | #    warning "A deprecated header has been included."
      |      ^~~~~~~
In file included from /usr/include/CGAL/Shape_detection/deprecated/Region_growing.h:48,
                 from /usr/include/CGAL/Shape_detection_3.h:22,
                 from /<<PKGBUILDDIR>>/SWIG_CGAL/User_packages/Shape_detection_3/Shape_detection_3.h:23,
                 from /<<PKGBUILDDIR>>/SWIG_CGAL/User_packages/Shape_detection_3/all_includes.h:12,
                 from /<<PKGBUILDDIR>>/build-python3.7/build-python/CGAL/CGAL_Shape_detection_3PYTHON_wrap.cxx:3144:
/usr/include/CGAL/internal/deprecation_warning.h:81:54: note: #pragma message: Warning: The header `<CGAL/Shape_detection/deprecated/Region_growing.h>` is deprecated. Please use `<CGAL/Shape_detection/Region_growing/Region_growing.h>` instead. Additional information: CGAL::Shape_detection_3::Region_growing<> has been replaced by the class CGAL::Shape_detection::Region_growing<>.
   81 | #    pragma message (CGAL_INTERNAL_DEPRECATED_MESSAGE)
      |                                                      ^
In file included from /usr/include/CGAL/Shape_detection/deprecated/Shape_detection_traits.h:30,
                 from /usr/include/CGAL/Shape_detection_3.h:23,
                 from /<<PKGBUILDDIR>>/SWIG_CGAL/User_packages/Shape_detection_3/Shape_detection_3.h:23,
                 from /<<PKGBUILDDIR>>/SWIG_CGAL/User_packages/Shape_detection_3/all_includes.h:12,
                 from /<<PKGBUILDDIR>>/build-python3.7/build-python/CGAL/CGAL_Shape_detection_3PYTHON_wrap.cxx:3144:
/usr/include/CGAL/internal/deprecation_warning.h:81:54: note: #pragma message: Warning: The header `<CGAL/Shape_detection/deprecated/Shape_detection_traits.h>` is deprecated. Please use `<CGAL/Shape_detection/Efficient_RANSAC/Efficient_RANSAC_traits.h>` instead. Additional information: CGAL::Shape_detection_3::Shape_detection_traits<> has been replaced by the class CGAL::Shape_detection::Efficient_RANSAC_traits<>.
   81 | #    pragma message (CGAL_INTERNAL_DEPRECATED_MESSAGE)
      |                                                      ^
In file included from /usr/include/CGAL/Shape_detection_3.h:29,
                 from /<<PKGBUILDDIR>>/SWIG_CGAL/User_packages/Shape_detection_3/Shape_detection_3.h:23,
                 from /<<PKGBUILDDIR>>/SWIG_CGAL/User_packages/Shape_detection_3/all_includes.h:12,
                 from /<<PKGBUILDDIR>>/build-python3.7/build-python/CGAL/CGAL_Shape_detection_3PYTHON_wrap.cxx:3144:
/usr/include/CGAL/internal/deprecation_warning.h:81:54: note: #pragma message: Warning: A deprecated header has been included. Additional information: CGAL::Shape_detection_3 namespace has been replaced by the namespace CGAL::Shape_detection.
   81 | #    pragma message (CGAL_INTERNAL_DEPRECATED_MESSAGE)
      |                                                      ^
In file included from /<<PKGBUILDDIR>>/SWIG_CGAL/User_packages/Shape_detection_3/all_includes.h:12,
                 from /<<PKGBUILDDIR>>/build-python3.7/build-python/CGAL/CGAL_Shape_detection_3PYTHON_wrap.cxx:3144:
/<<PKGBUILDDIR>>/SWIG_CGAL/User_packages/Shape_detection_3/Shape_detection_3.h:43:34: error: ‘Region_growing’ in namespace ‘CGAL::Shape_detection_3’ does not name a template type; did you mean ‘Region_growing_depr’?
   43 | typedef CGAL::Shape_detection_3::Region_growing<Traits>      Region_growing;
      |                                  ^~~~~~~~~~~~~~
      |                                  Region_growing_depr
make[4]: *** [SWIG_CGAL/User_packages/Shape_detection_3/CMakeFiles/CGAL_Shape_detection_3_python.dir/build.make:63: SWIG_CGAL/User_packages/Shape_detection_3/CMakeFiles/CGAL_Shape_detection_3_python.dir/__/__/__/build-python/CGAL/CGAL_Shape_detection_3PYTHON_wrap.cxx.o] Error 1
make[4]: Leaving directory '/<<PKGBUILDDIR>>/build-python3.7'
make[3]: *** [CMakeFiles/Makefile2:2430: SWIG_CGAL/User_packages/Shape_detection_3/CMakeFiles/CGAL_Shape_detection_3_python.dir/all] Error 2
make[3]: *** Waiting for unfinished jobs....
[ 46%] Linking CXX shared library ../../lib/libCGAL_Kernel_cpp.so
make[4]: Leaving directory '/<<PKGBUILDDIR>>/build-python3.7'
[ 46%] Built target CGAL_Kernel_cpp
make[3]: Leaving directory '/<<PKGBUILDDIR>>/build-python3.7'
make[2]: *** [Makefile:141: all] Error 2
make[2]: Leaving directory '/<<PKGBUILDDIR>>/build-python3.7'
make[1]: *** [debian/rules:61: override_dh_auto_build] Error 2
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
make: *** [debian/rules:36: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
--------------------------------------------------------------------------------
Build finished at 20200204-2111
```
[[Build log](https://launchpadlibrarian.net/463552035/buildlog_ubuntu-eoan-amd64.cgal-swig-bindings_0.0.2~564~12~202002042058~ubuntu19.10.1_BUILDING.txt.gz)]

Is there something I missed? Any specific option I should/should not use during the build?

Here are the packaging files:
main: https://github.com/thopiekar/cgal-packaging
swig: https://github.com/thopiekar/cgal-swig-bindings-packaging

Thanks!

**Comment by sgiraudot** [comment]
The Region Growing algorithm was completely rewritten (and extended) in [CGAL 5.0](https://www.cgal.org/2019/11/08/cgal50/). As the error messages suggest, you can still fallback to the now deprecated old version, but I would strongly advise switching to the new version (check [the manual](https://doc.cgal.org/latest/Shape_detection/#title10) for more information). @danston is there a guide somewhere for how to switch to the new API?

Note also that [some Shape Detection bindings were recently added to the official repository](https://github.com/CGAL/cgal-swig-bindings/pull/146), so you may want to switch to these, which would be even simpler.

**Comment by danston** [comment]
Hey. Yes, as @sgiraudot correctly explained, we strongly advise you to update your code to the new API, however you can still use the old code as in the example [here](https://doc.cgal.org/latest/Shape_detection/index.html#Shape_detection_DeprecatedComponents). Unfortunately, we do not have a specific guide on how to switch, but there are many examples in the [manual](https://doc.cgal.org/latest/Shape_detection/index.html#Shape_detection_RegionGrowing). In general, the switch should not be very painful. If you have any trouble, please let me know and I will try to guide you.

**Comment by thopiekar** [comment]
Great! Many thanks for your help already.

So the SWIG bindings are using this deprecated API? Or is something going wrong on my side.
Since there is a CGAL-4.x branch in the repo here, I would expect that the bindings in the branch master are that far updated that they could work with CGAL 5.x or master.

Or is there a misunderstanding on my side?

**Comment by sgiraudot** [comment]
Oops, sorry, I linked to a wrong PR (that was actually not integrated), this one actually integrated Shape Detection, with the current up-to-date API of course: https://github.com/CGAL/cgal-swig-bindings/pull/145

**Comment by thopiekar** [comment]
@sgiraudot No problem. When you mentioned the PR in your first message, I had this one in mind already. Remember that I saw this PR before. Great work by the way!

Sadly I'm still struggling why my build fails:
https://launchpadlibrarian.net/464858779/buildlog_ubuntu-focal-amd64.cgal-swig-bindings_0.0.2~565~18~202002131928~ubuntu20.04.1_BUILDING.txt.gz
As you can see in the list of downloaded packages, I'm downloading libcgal-dev from my PPA and I build CGAL packages in my PPA based on the latest 5.0.1 release.
However, the code claims that my version is still too old.

So the idea I have this: Could it be that the message appears also in other scenarios?
I heard that CGAL is a header-only library now. I'm not an expert, but what if I miss one of its dependencies? Will I get notifications and/or warnings from compiler macros? :confused: 
Do you see other reasons, why my build might fail?

**Comment by sloriot** [comment]
The first question you need to answer is why is there some errors with `SWIG_CGAL/User_packages/Shape_detection_3`. I suspect that there are some files lying around that shouldn't exist.

**Comment by thopiekar** [comment]
Well, if I could I would :grimacing:  The environment must be completely clean, because a minimal rootfs gets unpacked, then all dependencies are going to be installed and finally the source gets built.
So if there are some files missing, then they might miss in the CGAL packages.

**Comment by thopiekar** [comment]
@sloriot Thank you for the pointer!
I completely forgot that I'm still merging my own WIP implementation of shape_detection bindings in my build recipe.
I'll keep you posted whether #151 is needed to resolve the issue mentioned before.
