### ISSUE TITLE
Get "You are mising CGAL Library" when "pip install cgal-bindings", after using Homebrew installed CGAL 

### ISSUE THREAD

**Issue by Hui606** [CGAL/cgal-swig-bindings#153]
After I used "brew install cgal", I tried to install CGAL-bindings for python, but the pip told that "You are missing CGAL Library" as following. Could anyone tell me what goes wrong with my operation? Thanks a lot.

> KKMacBook-Pro:~ mdddd$ pip install cgal-bindings
Collecting cgal-bindings
  Using cached cgal-bindings-1.2.tar.gz (1.7 MB)
    ERROR: Command errored out with exit status 255:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/_z/_5mfh9hj2v39n4gzpvwc0bn80000gn/T/pip-install-qqknyqp6/cgal-bindings/setup.py'"'"'; __file__='"'"'/private/var/folders/_z/_5mfh9hj2v39n4gzpvwc0bn80000gn/T/pip-install-qqknyqp6/cgal-bindings/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/_z/_5mfh9hj2v39n4gzpvwc0bn80000gn/T/pip-install-qqknyqp6/cgal-bindings/pip-egg-info
         cwd: /private/var/folders/_z/_5mfh9hj2v39n4gzpvwc0bn80000gn/T/pip-install-qqknyqp6/cgal-bindings/
    Complete output (1 lines):
    You are missing the CGAL library
    ----------------------------------------
ERROR: Command errored out with exit status 255: python setup.py egg_info Check the logs for full command output.

**Comment by sloriot** [comment]
The current version of the pip package is not maintained by the CGAL project and rely on an older version of CGAL AFAIR (4.7?). I have no solution to propose other than compiling the bindings yourself.

**Comment by Hui606** [comment]
> The current version of the pip package is not maintained by the CGAL project and relies on an older version of CGAL AFAIR (4.7?). I have no solution to propose other than compiling the bindings yourself.

Thanks @sloriot. Does it mean if I install this "older version of CGAL", the pip command can be used?

**Comment by sloriot** [comment]
I haven't try it but it should.

**Comment by Hui606** [comment]
Hey guys, I just successfully installed the CGAL-bindings without using the pip commands. Here is how I did it.

Using the commands listed in the bottom of this page: https://github.com/CGAL/cgal-swig-bindings/wiki/Installation, but changed a little, which goes

> > git clone https://github.com/cgal/cgal-swig-bindings
> cd cgal-swig-bindings
> mkdir build/CGAL-5.0_release -p
> cd build/CGAL-5.0_release
> cmake -DCGAL_DIR=/usr/lib/CGAL -DBUILD_JAVA=OFF -DPYTHON_OUTDIR_PREFIX=../../examples/python ../..
> make -j 4
> cd ../../examples/python
> python test.py
... output of the example test.py...

Note: for this line `> mkdir build/CGAL-5.0_release -p` I couldn't create the folder so I create it manually. 

The above code is for python usage. If Java, you can just copy the code in that link.

**Comment by krober10nd** [comment]
Hey all, 

I'm facing a similar problem.

However, when I attempted the instructions above by Hui606, make -j 4 simply doesn't produce any output. 

The makefiles are generated by Cmake interestingly enough. 

All the relevant dependencies are installed as well.

Any help would be nice!

**Comment by Hui606** [comment]
Hey @krober10nd , I just tried my code again and everything goes well. 

When run `make -j 4`, the output should be this:
![image](https://user-images.githubusercontent.com/47696810/77098597-857cfe80-6a0a-11ea-9cb9-25a0140c107b.png)


I am not sure what you mean 

> The makefiles are generated by Cmake interestingly enough.

**Comment by krober10nd** [comment]
I see my mistake. After I ran `brew install cgal' cmake can't find the cgal lib. 

(base) keiths-MacBook-Pro:CGAL-5.0_release Keith$ cmake -DCGAL_DIR=/usr/lib/CGAL -DBUILD_JAVA=OFF -DPYTHON_OUTDIR_PREFIX=../../examples/python ../..
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found SWIG: /usr/local/bin/swig (found version "3.0.8") 
**-- NOTICE: CGAL-bindings requires the CGAL library 5.0 or later, and will not be compiled.**
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    PYTHON_OUTDIR_PREFIX

**Comment by krober10nd** [comment]
Just curious what's in your  -DCGAL_DIR=/usr/lib/CGAL direcotry @Hui606 ? The ccmake gui indicates it's looking for a FindCmake file.

**Comment by Hui606** [comment]
Good question @krober10nd , there is no directory `/usr/lib/CGAL` in my computer but the code can run correctly. I hope someone can answer this.

All the `FindXX.cmake` files are in folder `/usr/local/lib/cmake/CGAL`

**Comment by krober10nd** [comment]
Thanks! Printing some variables from the cmake script, it appears CGAL is indeed found but it's indicating it's version 4 so it doesn't satisfy the logic in the cmake lists script.

**Comment by krober10nd** [comment]
Ah, this was silly. I had an old copy of CGAL that I had manually installed and forgotten at some point. Removing that, reinstalling cgal with brew, everything is working now.

**Comment by gcaria** [comment]
In case this helps anyone, I had to add `-DBUILD_PYTHON=ON` to the cmake command to make it work, since for some reason for me the python build was disabled by default.
