### ISSUE TITLE
Does Python-bindings contain function "bisector()"?

### ISSUE THREAD

**Issue by Hui606** [CGAL/cgal-swig-bindings#154]
Hi, I am new to python CGAL and I cannot find any example that shows how to use "bisector()". I want to write something like `bisector(center,(10,20))`

Can anyone please tell me if this function is included in Python-bindings? If so, could you give an example? Thanks.

**Comment by sloriot** [comment]
It's not and I don't see why. I'm adding it.

**Comment by sloriot** [comment]
See https://github.com/CGAL/cgal-swig-bindings/commit/dcd0bb6bc9ffc2b5f5ea93a92bb574f9e32b1dfc
