### ISSUE TITLE
efficient_RANSAC: Executed ends with segmentation fault

### ISSUE THREAD

**Issue by thopiekar** [CGAL/cgal-swig-bindings#158]
See #157

**Comment by sgiraudot** [comment]
The normal map must be added before doing anything related to normals, see [the documentation](https://doc.cgal.org/latest/Point_set_3/classCGAL_1_1Point__set__3.html#acd87a6f1e03fdb0d1bec9111272043ae) and [the Point Set 3 example of the bindings](https://github.com/CGAL/cgal-swig-bindings/blob/master/examples/python/Point_set_3_example.py).

**Comment by thopiekar** [comment]
Many thanks for your help! I added the normal map to my modified example and it works fine now.
At the moment I face an issue with efficient_RANSAC. Hope you don't mind if I rename the issue here.

Whenever feeding the function with points and normals, I get segmentation faults.
If the dataset is large (100.000 points), efficient_RANSAC is running for some time, but then ending with a segmentation fault. So it seems to happen at somewhere at the end of the function.

The strange thing is that if I move the points and normals into a text file with .pwn extension, the example script works with it. Also, if I don't reload the file as in the latest version of my example script and convert every value into floats, it still crashes. The vertices' coordinates are originally saved in a Numpy array and their normals is calculated using cross product and finally normalized.

Below a link of the code I'm running here. I personally don't see any difference to the Shape_Detection example. It would be great, if you could take a look! :smile: 
https://github.com/tetonsim/is-cura-ui/blob/7a8eeaa42afd7ab553730286713f8f27cb533443/SmartSlicePlugin/shape_detection/ShapeDetectedNode.py#L99

Regarding this and the error about the missing normal map, it would be great, if the CGAL won't crash and show an error message instead I think. Seeing these segmentation faults make me scared actually :sweat_smile: 

-----------------

[ShapeDetection.crash.log](https://github.com/CGAL/cgal-swig-bindings/files/4257932/ShapeDetection.crash.log)
[ShapeDetection.pwn.log](https://github.com/CGAL/cgal-swig-bindings/files/4257933/ShapeDetection.pwn.log)

**Comment by sgiraudot** [comment]
At the beginning of `generate_point_cloud()`, you clear the point set, which removes all the properties (see [documentation](https://doc.cgal.org/latest/Point_set_3/classCGAL_1_1Point__set__3.html#a6d53149421c3d97c949192e0258bac66)). If that function is called, the shape map you create in the constructor is not valid anymore (and normal map too by the way) and the efficient RANSAC will push its input into invalid memory.
