### ISSUE TITLE
Add switch for Python2/Python3

### ISSUE THREAD

**Issue by roversch** [CGAL/cgal-swig-bindings#168]
Out of the box on Ubuntu 18.04, `python` refers to `python2`. 

I had to change following lines in `CMakeLists.txt` to compile for Python 3:

      find_package(PythonInterp 3 REQUIRED)
      find_package(PythonLibs 3 REQUIRED)

In the newer CMake versions, there is also FindPython2 and FindPython3 available.

**Comment by lrineau** [comment]
There are a lot of ongoing changes in PR #100. The selection of python will certainly change. We might drop the support for Python 2, anyway.

**Comment by lrineau** [comment]
We have dropped the support for Python 2 with #162.
