### ISSUE TITLE
cmake error configuring incomplete

### ISSUE THREAD

**Issue by Rayna-Zhang** [CGAL/cgal-swig-bindings#171]
#`cmake -DCGAL_DIR=/usr/lib/CGAL -DBUILD_JAVA=OFF -DPYTHON_OUTDIR_PREFIX=../../examples/python ../..`
The error:
```
CMake Error at CMakeLists.txt:36 (if):
  if given arguments:
    "CGAL_FOUND" "AND" "GREATER" "4"
  Unknown arguments specified
-- Configuring incomplete, errors occurred!

```

**Comment by sloriot** [comment]
What cmake version are you using? What CGAL version are you using?

**Comment by ArnoChenFx** [comment]
Have you configured CGAL(https://github.com/CGAL/cgal/releases)?

**Comment by Rayna-Zhang** [comment]
> What cmake version are you using? What CGAL version are you using?

3.14

**Comment by Rayna-Zhang** [comment]
> Have you configured CGAL(https://github.com/CGAL/cgal/releases)?

Thank you, I re-congifured CGAL, and now it's ok. 3Q
