### ISSUE TITLE
No module CGAL_Point_set_processing_3

### ISSUE THREAD

**Issue by Rayna-Zhang** [CGAL/cgal-swig-bindings#173]
I try to run Point_set_processing_3_example.py, but It failed with:
ModuleNotFoundError: No module named 'CGAL.CGAL_Point_set_processing_3'

is it possible to use this package now? or is there sth I missed?
Thank you

**Comment by sloriot** [comment]
Did you compile it? Do you have an issue with all the packages or only this one?

**Comment by Rayna-Zhang** [comment]
> Did you compile it? Do you have an issue with all the packages or only this one?

Yeah， I try test.py and it's ok, but when I try run Point_set_processing_3_example.py, it failed.

**Comment by sloriot** [comment]
Strange. Do you have `CGAL/CGAL_Point_set_processing_3.py` in your python build directory?

**Comment by Rayna-Zhang** [comment]
> Strange. Do you have `CGAL/CGAL_Point_set_processing_3.py` in your python build directory?
no this one, only its `.cxx`

**Comment by sloriot** [comment]
You might have a compilation error or a cmake message saying it cannot be compiled.

**Comment by Rayna-Zhang** [comment]
> You might have a compilation error or a cmake message saying it cannot be compiled.
Yeah,  thanks for giving me clues. I find that for using `Point_set_processing`, it needs the dependency `eigen`. I install it and re-compile again and it now works. Thank you :)
