### ISSUE TITLE
Point_set_3 with Point_2

### ISSUE THREAD

**Issue by odysseusPolytropos** [CGAL/cgal-swig-bindings#183]
Hi folks,

I would like to use a `CGAL::Point_set_3` with `Point_2`.

Being new to SWIG I was wondering how a proper support that in the cgal-swig-bindings could look like.

The current SWIG implementation of `Point_set_3` (`PS3`) is a wrapper around `CGAL::Point_set_3<Kernel::Point_3>`. The reasoning for using `Point_3` is - as far as I understand - that some target languages don't support templates (Python is the one to blame here, I guess?). Therefore `PS3` supports only `Point_3`, which is okay most of the time, except if you want to use `Point_2` instead.

These ideas came to my mind:

1. Just creating a swig module `Point_set_2` as `CGAL::Point_set_3<Kernel::Point_2>` analogue to `PS3` does not seem to be a good decision, since there is a already a package named `CGAL::Point_set_2`, which is quite different to `CGAL::Point_set_3` and would be confusing/colliding if someone would like to support `CGAL::Point_set_2` in the SWIG bindings. Maybe another name like `Point_set_3_2d` could sail around this issue, but does not fit in the current naming scheme.

2. Extend `PS3` somehow that it supports both `Point_2` and `Point_3` under the hood. Here I'm not sure how this could fit in the current concept of the cgal-swig-bindings.

If there is something I could contribute, I would be willing to do so and appreciate some hints pointing in the right direction.

**Comment by lrineau** [comment]
Before you do anything using SWIG, you should test if the C++ class template `CGAL::Point_set_3` can work correctly with `Kernel::Point_2`.

@sgiraudot Do you have a clue?

**Comment by sgiraudot** [comment]
The C++ class should work fine, it does not really do anything with the type, for all we know you could template it with any object you want. The only thing I would be careful with would be the second template parameter, if you don't do `Point_set_3<Point_2, Vector_2>`, then it will default to `Point_set_3<Point_2, Vector_3>` using kernel traits, which is probably not what you want.

About the SWIG version, I honestly have no idea what's the best thing to do. This is the first I've heard from someone who wants to use `Point_set_3` in 2D, and I agree that naming it `Point_set_2` would bring too much confusion with the existing `CGAL::Point_set_2` which has nothing to do with this.

**Comment by odysseusPolytropos** [comment]
Since I'm using numpy for 2D point computation and performance is not too relevant, this request is not relevant for me anymore. If anyone else thinks this would be a good idea, it is not to hard to open a new issue.
