### ISSUE TITLE
Get vertex id when parsing surface from reconstruction

### ISSUE THREAD

**Issue by tuanng-cognite** [CGAL/cgal-swig-bindings#185]
I followed the example Advancing_front_reconstruction_example.java. My goal is to get the same data as written in output file.
```
OFF
5 3 0

0 0 0
1 0 0
1 1 0
0 1 0
1 2 0
3  2 4 3
3  3 0 1
3  1 2 3
```
The last three lines are the triangles represented by vertex ids.

In java code, I can get the vertex coordinates but not its id.
```java
for (Polyhedron_3_Facet_handle facet : P.facets()) {
      Polyhedron_3_Halfedge_around_facet_circulator polyhedron_3_halfedge_handles = facet .facet_begin();
      Point_3 p1 = polyhedron_3_halfedge_handles.next().vertex().point();
      Point_3 p2 = polyhedron_3_halfedge_handles.next().vertex().point();
      Point_3 p3 = polyhedron_3_halfedge_handles.next().vertex().point();
}
```
polyhedron_3_halfedge_handles.next().vertex().id() always return  -1.

Is it that we currently don't support getting id or am I doing it wrong?

**Comment by AlainLich** [comment]
I have the same issue but with the *Python bindings!*

**Comment by sloriot** [comment]
There is an `id` fields in the vertices that you can set with `v.set_id(id))` and access with `v.id()`.
In your can you need intial pass on vertices to set the id of each vertex and then when iterating over faces you can get back the id.

**Comment by AlainLich** [comment]
Thanks, this works,  I tried
a) an int id: works OK
b) (getting more courageous), an str id: does not work, I get 
```count=0
for v in P.vertices():
    v.set_id(f"ID{count}")
    count+= 1
for v in P.vertices():
    print(f"Point:{v.point()}\tid={v.id()}")

~/test/CGAL/cgal-swig-build/build-python/CGAL/CGAL_Polyhedron_3.py in set_id(self, i)
    251 
    252     def set_id(self, i):
--> 253         return _CGAL_Polyhedron_3.Polyhedron_3_Vertex_handle_set_id(self, i)
    254 
    255     def set_point(self, p):

TypeError: in method 'Polyhedron_3_Vertex_handle_set_id', argument 2 of type 'int'
``` 
However the type required is not easy to grasp from the description in file `build-python/CGAL/CGAL_Polyhedron_3.py`, and I wonder where to look in the C++ or manual to answer such questions. *The error message is however very clear about the expected type.*

**Thanks for your quick answer**, the integer case suffices for what I want to do at this time, but with Python, I am getting used to rather loose typing
