### ISSUE TITLE
ImportError: DLL load failed with vcpkg CGAL install Windows 10 x64 

### ISSUE THREAD

**Issue by fridasvelander** [CGAL/cgal-swig-bindings#200]
Hi, 

I am having problem running the python examples. I have a working installation of CGAL 5.3 (installed with vcpkg) and build the bindings with Visual studio 2019 in Release mode.

**cmake -DCGAL_DIR=C:\dev\vcpkg\installed\x64-windows\share\cgal -DCMAKE_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_PYTHON=ON -DBUILD_JAVA=OFF ../** 

See output of configure at the bottom of this page.

After building in Visual studio I get the build-python directory with .pyd and .py files, and a Release directory with .lib and .exp files. Whatever example in the examples/python directory, I get an error similar to the following:

  **File "test_t2.py", line 2, in <module>
    from CGAL.CGAL_Kernel import Point_2
  File "C:\dev\CGAL\cgal-swig-bindings\build\build-python\CGAL\CGAL_Kernel.py", line 15, in <module>
    from . import _CGAL_Kernel
ImportError: DLL load failed: The specified module could not be found.** 

I have exported PYTHONPATH=C:\dev\CGAL\cgal-swig-bindings\build\build-python\;C:\dev\CGAL\cgal-swig-bindings\build\build-python\CGAL;C:\dev\CGAL\cgal-swig-bindings\build\build-python\CGAL\Release\, but no luck.

What am I doing wrong? Thanks for any help!

**-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.29.30133.0
-- The CXX compiler identification is MSVC 19.29.30133.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Visual Leak Detector (VLD) is not found.
-- Using header-only CGAL
-- Targetting Visual Studio 16 2019
-- Target build enviroment supports auto-linking
-- Using VC toolset 142.
-- Generator uses intermediate configuration directory: $(Configuration)
-- Found GMP: debug;C:/dev/vcpkg/installed/x64-windows/debug/lib/gmpd.lib;optimized;C:/dev/vcpkg/installed/x64-windows/lib/gmp.lib
-- Found MPFR: C:/dev/vcpkg/installed/x64-windows/lib/mpfr.lib
-- Found Boost: C:/dev/vcpkg/installed/x64-windows/include (found suitable version "1.76.0", minimum required is "1.48")
-- Boost include dirs: C:/dev/vcpkg/installed/x64-windows/include
-- Boost libraries:
-- Found ZLIB: optimized;C:/dev/vcpkg/installed/x64-windows/lib/zlib.lib;debug;C:/dev/vcpkg/installed/x64-windows/debug/lib/zlibd.lib (found version "1.2.11")
-- Found SWIG: C:/Program Files/swigwin-4.0.2/swig.exe (found version "4.0.2")
-- Multi-configuration CMake generator: cannot display flags
-- Requested component: ImageIO
-- NOTICE: Intel TBB was not found. Parallelism will be disabled.
-- BUILD_RUBY is set to OFF: no CGAL-bindings for Ruby will be generated.
-- Found Python: C:/Users/fsvee09386/AppData/Local/Programs/Python/Python39/python.exe (found version "3.9.5") found components: Interpreter Development Development.Module Development.Embed
-- BUILD_JAVA is set to OFF: no CGAL-bindings for Java will be generated.
-- Found Python libs.
-- CGAL-SWIG Python files and libraries will be written in C:/dev/CGAL/cgal-swig-bindings/build/build-python/CGAL.
-- Now adding packages
-- NOTICE : LAS IO requires LASlib and will not be available.
-- Found Eigen3: C:/dev/vcpkg/installed/x64-windows/include/eigen3 (found suitable version "3.3.9", minimum required is "3.1.0")
CMake Deprecation Warning at C:/dev/vcpkg/installed/x64-windows/share/cgal/UseEigen3.cmake:11 (message):
  This file UseEigen.cmake is deprecated, and the imported target
  `CGAL::Eigen3_support` from CGAL_Eigen3_support.cmake should be used
  instead.
Call Stack (most recent call first):
  SWIG_CGAL/Point_set_processing_3/CMakeLists.txt:6 (include)

CMake Deprecation Warning at C:/dev/vcpkg/installed/x64-windows/share/cgal/UseEigen3.cmake:11 (message):
  This file UseEigen.cmake is deprecated, and the imported target
  `CGAL::Eigen3_support` from CGAL_Eigen3_support.cmake should be used
  instead.
Call Stack (most recent call first):
  SWIG_CGAL/Shape_detection/CMakeLists.txt:6 (include)

-- Found Boost: C:/dev/vcpkg/installed/x64-windows/include (found version "1.76.0") found components: serialization iostreams regex
-- Found Boost: C:/dev/vcpkg/installed/x64-windows/include (found version "1.76.0")  missing components: bzip2 zlib
CMake Deprecation Warning at C:/dev/vcpkg/installed/x64-windows/share/cgal/UseEigen3.cmake:11 (message):
  This file UseEigen.cmake is deprecated, and the imported target
  `CGAL::Eigen3_support` from CGAL_Eigen3_support.cmake should be used
  instead.
Call Stack (most recent call first):
  SWIG_CGAL/Classification/CMakeLists.txt:34 (include)

-- Found Eigen3: C:/dev/vcpkg/installed/x64-windows/include/eigen3 (found suitable version "3.3.9", minimum required is "3.2.0")
CMake Deprecation Warning at C:/dev/vcpkg/installed/x64-windows/share/cgal/UseEigen3.cmake:11 (message):
  This file UseEigen.cmake is deprecated, and the imported target
  `CGAL::Eigen3_support` from CGAL_Eigen3_support.cmake should be used
  instead.
Call Stack (most recent call first):
  CMakeLists.txt:225 (include)

-- Configuring done
-- Generating done
-- Build files have been written to: C:/dev/CGAL/cgal-swig-bindings/build**

**Comment by adamgranthendry** [comment]
Try [this link](https://test.pypi.org/project/cgal/). Looks like they're doing something experimental. Install it using:

```
> pip install -i https://test.pypi.org/simple/ cgal
```

**Comment by lrineau** [comment]
> I have exported PYTHONPATH=C:\dev\CGAL\cgal-swig-bindings\build\build-python;C:\dev\CGAL\cgal-swig-bindings\build\build-python\CGAL;C:\dev\CGAL\cgal-swig-bindings\build\build-python\CGAL\Release, but no luck.

I think the error is probably that your `PATH` variable should contain the directories containing all the dependencies of the CGAL Python modules, in particular the GMP and MPFR libraries.

But I cannot be sure, because I do not have a Windows machine (but Linux).

**Comment by fridasvelander** [comment]
@lrineau Thanks. 

The files gmp.dll, mpfr-6.dll and boost_serialization-vc142-mt-x64-1_76.dll are somehow generated in C:\dev\CGAL\cgal-swig-bindings\build\build-python\CGAL as I build the project. Anyway I try to export  
PYTHONPATH=C:\dev\CGAL\cgal-swig-bindings\build\build-python;C:\dev\CGAL\cgal-swig-bindings\build\build-python\CGAL;C:\dev\CGAL\cgal-swig-bindings\build\build-python\CGAL\Release;C:/dev/vcpkg/installed/x64-windows/lib/;C:/dev/vcpkg/installed/x64-windows/include

as the GMP, MPFR, Boost etc headers and .lib files are installed there. My CGAL 5.3 installation is in C:/dev/vcpkg/installed/x64-windows/include/CGAL. 

Is there any problem that I'm "-- Using header-only CGAL"?

**Comment by lrineau** [comment]
It this issue still alive? @fridasvelander, you are the reporter... Have you eventually found a fix, or a workaround for that issue?

**Comment by Xtian-hub** [comment]
I have same error, some one have answer?
(base) PS C:\Users\HIT> & G:/anaconda3/envs/green/python.exe h:/cgal-swig-bindings-6.0.1.post202410241521/examples/python/test.py
Traceback (most recent call last):
  File "h:\cgal-swig-bindings-6.0.1.post202410241521\examples\python\test.py", line 5, in <module>
    from CGAL import CGAL_Triangulation_3
  File "H:\cgal-swig-bindings-6.0.1.post202410241521\build\build-python\CGAL\CGAL_Triangulation_3.py", line 12, in <module>
    from . import _CGAL_Triangulation_3
ImportError: DLL load failed while importing _CGAL_Triangulation_3:

**Comment by lrineau** [comment]
@Xtian-hub It seems you have downloaded a tarball of `cgal-swig-bindings` version `6.0.1.post202410241521`, and unpacked it to `h:/cgal-swig-bindings-6.0.1.post202410241521`. You should know that the installation of the Python CGAL modules is to be done with:

    pip install cgal

or with Conda, with the `cgal` package.

- For the Python package (from PyPI), see https://pypi.org/project/cgal/.
- For the Conda package, see https://anaconda.org/conda-forge/cgal.

Once either of that is installed, and only then, you will be able to run the examples found in the subdirectory `examples/python/`.
