### ISSUE TITLE
triangulate_hole_polyline throws assertion

### ISSUE THREAD

**Issue by odysseusPolytropos** [CGAL/cgal-swig-bindings#207]
I'm trying to build the CGAL SWIG bindings on arch linux (with this PKGBUILD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cgal-swig-bindings ). The build works fine, but one of the python tests fails.

The call of `CGAL_Polygon_mesh_processing.triangulate_hole_polyline()` in the function` test_hole_filling_functions` of `pythontest_test_pmp.py ` fails with the following assertion:

> user@pc ~/.c/a/c/s/c/e/python (makepkg) [SIGABRT]> python test_pmp.py
Testing meshing functions...
Testing hole filling functions...
/usr/include/c++/11.1.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = CGAL::Point_3<CGAL::Epick>; _Alloc = std::allocator<CGAL::Point_3<CGAL::Epick> >; std::vector<_Tp, _Alloc>::reference = CGAL::Point_3<CGAL::Epick>&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
fish: Job 2, 'python test_pmp.py' terminated by signal SIGABRT (Abbruch)

I'm using Python 3.10 and I'm having the newest git checkout of CGAL installed (5.3.x at Commit 
https://github.com/CGAL/cgal/commit/80b07c5e39b8d4204108419fd26ad01c9473bcbf ).

If any other details are of interest, I'm happy to supply them.

**Comment by sloriot** [comment]
Should be fixed by 2479e35 (already pushed in `main`)
