### ISSUE TITLE
Polyhedron_3 intersection

### ISSUE THREAD

**Issue by LachlanGray** [CGAL/cgal-swig-bindings#214]
Hello,

Is there a way to detect the intersection of two Polyhedron_3's? I was hoping to use [do_intersect](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__intersection__grp.html) but Polyhedron_3 isn't supported in the bindings. 

I was wondering if there is still a way I can do this, or if it would possible to add Polyhedron_3 to the list of kernel primitives. 

Thank you

**Comment by LachlanGray** [comment]
If it's straight forward, I'd be happy to add bindings for `Polygon_mesh_processing::do_intersect`

**Comment by sloriot** [comment]
Added in 7474cf1

**Comment by LachlanGray** [comment]
Thanks! Very much appreciated

**Comment by LachlanGray** [comment]
Hi sorry I'm back again, but the binding should return bool instead of void. It works for me by changing it to look like `does_self_intersect` two functions above it

**Comment by sloriot** [comment]
Sorry, just fixed it.
