### ISSUE TITLE
alpha_wrap_3.h is missing

### ISSUE THREAD

**Issue by Marosso** [CGAL/cgal-swig-bindings#216]
With the newest commit, the cmake build fails:
> fatal error: CGAL/alpha_wrap_3.h: No such file or directory

I guess it should be `SWIG_CGAL/...`, but that file is not there, yet.

Am I missing something or could you add it? Thanks.

**Comment by sloriot** [comment]
You need CGAL 5.5. I must update cmake to not try to compile it if the version of CGAL is not at least 5.5.

**Comment by Marosso** [comment]
Thanks for the fast reply. You are right. The last commits are not compatible with libcgal-dev on Debian. I'll stick to tag 5.5.post202207291543 for now.

**Comment by lrineau** [comment]
Alternatively, @Marosso, you can install the Python bindings, if that is the target language that you want, with the `pip` command:

    pip install cgal

CGAL is now in the Python Package Index (PyPI): https://pypi.org/project/cgal/.
