### ISSUE TITLE
c# bindings

### ISSUE THREAD

**Issue by mariuszhermansdorfer** [CGAL/cgal-swig-bindings#223]
Thanks for creating and maintaining this repo! 

I was able to successfully build the Python bindings, but is there a way to do it for c# as well? 
My knowledge of SWIG and Cmake is very limited but I'm willing to learn.

Any pointers in the right direction would be much appreciated!

**Comment by sloriot** [comment]
If you look  in the main `CMakeLists.txt` file, you will see some lines with `RUBY` that provides some kind of minimal support for ruby. I guess the best way to start is to duplicate what is done for ruby and try to adapt it to C#.

**Comment by lrineau** [comment]
@mariuszhermansdorfer Once you manage to get something working, please consider sharing your modification via a pull-request.

**Comment by mariuszhermansdorfer** [comment]
Will look at it and report back. Thanks for the pointes.
