### ISSUE TITLE
Compilation errors (was "error on cmake")

### ISSUE THREAD

**Issue by sendreams** [CGAL/cgal-swig-bindings#225]
use the latest version: 5.5.1,  macos 13.2, while compile meet 2 errors.

> 3 warnings generated.
> [ 82%] Linking CXX shared module /Users/chenhong/git/cgal-swig-bindings/examples/java/lib/libCGAL_Point_set_3.jnilib
> [ 82%] Built target CGAL_Point_set_3
> [ 83%] Building CXX object SWIG_CGAL/Box_intersection_d/CMakeFiles/CGAL_Box_intersection_d.dir/__/__/examples/java/CGAL/Box_intersection_d/CGAL_Box_intersection_dJAVA_wrap.cxx.o
> /Users/chenhong/git/cgal-swig-bindings/examples/java/CGAL/Classification/CGAL_ClassificationJAVA_wrap.cxx:874:104: error: call to constructor of 'Feature_set_wrapper<CGAL_Feature_set, Feature_wrapper<CGAL_Feature>>::Feature' (aka 'Feature_wrapper<CGAL::Classification::Feature_handle>') is ambiguous
>   *(Feature_set_wrapper< CGAL_Feature_set,Feature_wrapper< CGAL_Feature > >::Feature **)&jresult = new Feature_set_wrapper< CGAL_Feature_set,Feature_wrapper< CGAL_Feature > >::Feature(result);
>                                                                                                        ^                                                                                ~~~~~~
> /Users/chenhong/git/cgal-swig-bindings/SWIG_CGAL/Classification/Feature_set.h:13:7: note: candidate constructor (the implicit move constructor)
> class Feature_wrapper
>       ^
> /Users/chenhong/git/cgal-swig-bindings/SWIG_CGAL/Classification/Feature_set.h:13:7: note: candidate constructor (the implicit copy constructor)
> /Users/chenhong/git/cgal-swig-bindings/SWIG_CGAL/Classification/Feature_set.h:19:3: note: candidate constructor
>   Feature_wrapper (Feature_base base) : data_sptr (new Feature_base(base)) { }
>   ^
> [ 84%] Linking CXX shared module /Users/chenhong/git/cgal-swig-bindings/examples/java/lib/libCGAL_Box_intersection_d.jnilib
> [ 84%] Built target CGAL_Box_intersection_d
> [ 85%] Building CXX object SWIG_CGAL/Advancing_front_surface_reconstruction/CMakeFiles/CGAL_Advancing_front_surface_reconstruction.dir/__/__/examples/java/CGAL/Advancing_front_surface_reconstruction/CGAL_Advancing_front_surface_reconstructionJAVA_wrap.cxx.o
> [ 86%] Linking CXX shared module /Users/chenhong/git/cgal-swig-bindings/examples/java/lib/libCGAL_Shape_detection.jnilib
> [ 86%] Built target CGAL_Shape_detection
> [ 87%] Building CXX object SWIG_CGAL/Polygon_mesh_processing/CMakeFiles/CGAL_Polygon_mesh_processing.dir/__/__/examples/java/CGAL/Polygon_mesh_processing/CGAL_Polygon_mesh_processingJAVA_wrap.cxx.o
> 1 error generated.
> make[2]: *** [SWIG_CGAL/Classification/CMakeFiles/CGAL_Classification.dir/__/__/examples/java/CGAL/Classification/CGAL_ClassificationJAVA_wrap.cxx.o] Error 1
> make[1]: *** [SWIG_CGAL/Classification/CMakeFiles/CGAL_Classification.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> In file included from /Users/chenhong/git/cgal-swig-bindings/examples/java/CGAL/Polygon_mesh_processing/CGAL_Polygon_mesh_processingJAVA_wrap.cxx:566:
> In file included from /opt/homebrew/include/CGAL/polygon_mesh_processing.h:49:
> In file included from /opt/homebrew/include/CGAL/Polygon_mesh_processing/smooth_mesh.h:21:
> /opt/homebrew/include/CGAL/Installation/internal/deprecation_warning.h:80:6: warning: "A deprecated header has been included." [-W#warnings]
> #    warning "A deprecated header has been included."
>      ^
> [ 87%] Linking CXX shared module /Users/chenhong/git/cgal-swig-bindings/examples/java/lib/libCGAL_Advancing_front_surface_reconstruction.jnilib
> [ 87%] Built target CGAL_Advancing_front_surface_reconstruction
> [ 87%] Linking CXX shared module /Users/chenhong/git/cgal-swig-bindings/examples/java/lib/libCGAL_Point_set_processing_3.jnilib
> [ 87%] Built target CGAL_Point_set_processing_3
> 1 warning generated.
> [ 88%] Linking CXX shared module /Users/chenhong/git/cgal-swig-bindings/examples/java/lib/libCGAL_Polygon_mesh_processing.jnilib
> [ 88%] Built target CGAL_Polygon_mesh_processing
> make: *** [all] Error 2

**Comment by sendreams** [comment]
the total log 
[info.log](https://github.com/CGAL/cgal-swig-bindings/files/10733493/info.log)

**Comment by sendreams** [comment]
i have make a video for compile 
[https://youtu.be/2iY6EQEKoL4](url)

**Comment by sendreams** [comment]
https://youtu.be/2iY6EQEKoL4

**Comment by lrineau** [comment]
Hi @sendreams. Thanks for the issue report. There is indeed a compilation error in `CGAL_Classification/`. We will try to find a solution.

**Comment by sendreams** [comment]
hi, @lrineau ,thanks
Is there instructions for compiling and using under windows. i have compile in windows, but result is a lot of dll files, i confuse about how to using these dll files in eclipse? I'm sorry, but I'm really not good at this. I searched for many days, but I couldn't find a way to use it.

**Comment by sloriot** [comment]
The compilation error should be fixed now (a regression in SWIG AFAIU)

**Comment by sendreams** [comment]
> 
hi, @sloriot 
thanks, i will be test later and feeback.

**Comment by sendreams** [comment]
hi, @sloriot this time compile is ok. but run test_kernel failure. the output is

> [ 97%] Built target CGAL_AABB_tree
[ 98%] Linking CXX shared module /Users/chenhong/git/cgal-swig-bindings/examples/java/lib/libCGAL_Polygon_mesh_processing.jnilib
[ 98%] Built target CGAL_Polygon_mesh_processing
[ 99%] Linking CXX shared module /Users/chenhong/git/cgal-swig-bindings/examples/java/lib/libCGAL_Surface_mesher.jnilib
[ 99%] Built target CGAL_Surface_mesher
[100%] Linking CXX shared module /Users/chenhong/git/cgal-swig-bindings/examples/java/lib/libCGAL_Mesh_3.jnilib
[100%] Built target CGAL_Mesh_3
(base) chenhong@ChenhonacStudio CGAL-5.0_release % cd ../../
(base) chenhong@ChenhonacStudio cgal-swig-bindings % cd examples/java
(base) chenhong@ChenhonacStudio java % java test_kernel
Exception in thread "main" java.lang.NoClassDefFoundError: CGAL/Kernel/Point_2
	at test_kernel.main(test_kernel.java:19)
Caused by: java.lang.ClassNotFoundException: CGAL.Kernel.Point_2
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 1 more
(base) chenhong@ChenhonacStudio java % export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:lib
(base) chenhong@ChenhonacStudio java % pwd
/Users/chenhong/git/cgal-swig-bindings/examples/java
(base) chenhong@ChenhonacStudio java % java test_kernel
Exception in thread "main" java.lang.NoClassDefFoundError: CGAL/Kernel/Point_2
	at test_kernel.main(test_kernel.java:19)
Caused by: java.lang.ClassNotFoundException: CGAL.Kernel.Point_2
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 1 more
(base) chenhong@ChenhonacStudio java %

**Comment by lrineau** [comment]
@sendreams You need to set the [Java class path](https://en.wikipedia.org/wiki/Classpath), so that the java virtual machine finds the CGAL classes generated by SWIG.

**Comment by sendreams** [comment]
hi, @lrineau , i know how to set java class path, if not set java class path, the error is like below:

> (base) chenhong@ChenhonacStudio java % java test_kernel
Native code library CGAL_Kernel failed to load.
java.lang.UnsatisfiedLinkError: no CGAL_Kernel in java.library.path: [/Users/chenhong/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
Exception in thread "main" java.lang.UnsatisfiedLinkError: no CGAL_Kernel in java.library.path: [/Users/chenhong/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2673)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at CGAL.Kernel.CGAL_KernelJNI.<clinit>(CGAL_KernelJNI.java:15)
	at CGAL.Kernel.Point_2.<init>(Point_2.java:60)
	at test_kernel.main(test_kernel.java:19)

**Comment by sendreams** [comment]
i have compile in debian, and the testing is ok.

**Comment by lrineau** [comment]
> (base) chenhong@ChenhonacStudio CGAL-5.0_release % cd ../../
> (base) chenhong@ChenhonacStudio cgal-swig-bindings % cd examples/java
> (base) chenhong@ChenhonacStudio java % java test_kernel
> Exception in thread "main" java.lang.NoClassDefFoundError: CGAL/Kernel/Point_2
> at test_kernel.main(test_kernel.java:19)
> Caused by: java.lang.ClassNotFoundException: CGAL.Kernel.Point_2
> at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
> at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> ... 1 more
> (base) chenhong@ChenhonacStudio java % export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:lib

It might be the `LD_LIBRARY_PATH` that is wrong. In the build directory, before `cd ../../`, you should set it to: `${LD_LIBRARY_PATH}:$PWD/lib`, so that the `lib/` sub-directory of the build directory is added to the library path.

**Comment by sendreams** [comment]
> Last login: Wed Feb 22 17:13:58 on ttys001
(base) chenhong@ChenhonacStudio ~ % export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/Users/chenhong/git/cgal-swig-bindings/build/CGAL-5.0_release/lib
(base) chenhong@ChenhonacStudio ~ % cd /Users/chenhong/git/cgal-swig-bindings/ex
amples/java
(base) chenhong@ChenhonacStudio java % echo $LD_LIBRARY_PATH
:/Users/chenhong/git/cgal-swig-bindings/build/CGAL-5.0_release/lib
(base) chenhong@ChenhonacStudio java % java test_kernel
Native code library CGAL_Kernel failed to load.
java.lang.UnsatisfiedLinkError: no CGAL_Kernel in java.library.path: [/Users/chenhong/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
Exception in thread "main" java.lang.UnsatisfiedLinkError: no CGAL_Kernel in java.library.path: [/Users/chenhong/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2673)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at CGAL.Kernel.CGAL_KernelJNI.<clinit>(CGAL_KernelJNI.java:15)
	at CGAL.Kernel.Point_2.<init>(Point_2.java:60)
	at test_kernel.main(test_kernel.java:19)
(base) chenhong@ChenhonacStudio java % export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/Users/chenhong/git/cgal-swig-bindings/examples/java/lib
(base) chenhong@ChenhonacStudio java % echo $LD_LIBRARY_PATH
:/Users/chenhong/git/cgal-swig-bindings/build/CGAL-5.0_release/lib:/Users/chenhong/git/cgal-swig-bindings/examples/java/lib
(base) chenhong@ChenhonacStudio java % java test_kernel
Native code library CGAL_Kernel failed to load.
java.lang.UnsatisfiedLinkError: no CGAL_Kernel in java.library.path: [/Users/chenhong/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
Exception in thread "main" java.lang.UnsatisfiedLinkError: no CGAL_Kernel in java.library.path: [/Users/chenhong/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2673)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at CGAL.Kernel.CGAL_KernelJNI.<clinit>(CGAL_KernelJNI.java:15)
	at CGAL.Kernel.Point_2.<init>(Point_2.java:60)
	at test_kernel.main(test_kernel.java:19)
(base) chenhong@ChenhonacStudio java %

if i copy the test_kernel.class file to '../examples/java/lib' folder, it will be show  'java.lang.NoClassDefFoundError: CGAL/Kernel/Point_2' error.

**Comment by lrineau** [comment]
Probably you have dependencies, such as GMP and MPFR, that are not in system directories. Their installation directories should be added to `LD_LIBRARY_PATH` as well.

On my Linux Fedora (version 38) machine: I have everything installed by system packages, and then the dependencies are found automatically. Try this command and compare with what I get:
```shellsession 
[lrineau@fernand]~/Git/cgal-swig-bindings/build/RelWithDebInfo% ldd build-java/lib/libCGAL_Kernel.so 
        linux-vdso.so.1 (0x00007fe06ce0f000)
        libCGAL_Kernel_cpp.so => /home/lrineau/Git/cgal-swig-bindings/build/RelWithDebInfo/lib/libCGAL_Kernel_cpp.so (0x00007fe06cb20000)
        libCGAL_Java_cpp.so => /home/lrineau/Git/cgal-swig-bindings/build/RelWithDebInfo/lib/libCGAL_Java_cpp.so (0x00007fe06cb1b000)
        libgmpxx.so.4 => /lib64/libgmpxx.so.4 (0x00007fe06cae0000)
        libmpfr.so.6 => /lib64/libmpfr.so.6 (0x00007fe06ca2e000)
        libgmp.so.10 => /lib64/libgmp.so.10 (0x00007fe06c987000)
        libstdc++.so.6 => /usr/local/lib64/libstdc++.so.6 (0x00007fe06c600000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fe06c8a7000)
        libgcc_s.so.1 => /usr/local/lib64/libgcc_s.so.1 (0x00007fe06c882000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fe06c423000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe06ce11000)
```

**Comment by sendreams** [comment]
> (base) chenhong@ChenhonacStudio lib % otool -L libCGAL_Kernel_cpp.dylib
libCGAL_Kernel_cpp.dylib:
	@rpath/libCGAL_Kernel_cpp.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/homebrew/opt/gmp/lib/libgmpxx.4.dylib (compatibility version 11.0.0, current version 11.1.0)
	/opt/homebrew/opt/mpfr/lib/libmpfr.6.dylib (compatibility version 9.0.0, current version 9.0.0)
	/opt/homebrew/opt/gmp/lib/libgmp.10.dylib (compatibility version 15.0.0, current version 15.1.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.36.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
(base) chenhong@ChenhonacStudio lib %

**Comment by lrineau** [comment]
All seems fine. :confused: 

Note that, if you are on MacOS, as far as I know `DYLD_LIBRARY_PATH` is used by the dynamic load, instead of `LD_LIBRARY_PATH`.

**Comment by sendreams** [comment]
> (base) chenhong@ChenhonacStudio lib % export DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}:/Users/chenhong/git/cgal-swig-bindings/build/CGAL-5.0_release/lib
(base) chenhong@ChenhonacStudio lib % cd ../../..
(base) chenhong@ChenhonacStudio cgal-swig-bindings % cd examples/java
(base) chenhong@ChenhonacStudio java % java test_kernel
Native code library CGAL_Kernel failed to load.
java.lang.UnsatisfiedLinkError: no CGAL_Kernel in java.library.path: [., /Users/chenhong/git/cgal-swig-bindings/build/CGAL-5.0_release/lib, /Users/chenhong/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
Exception in thread "main" java.lang.UnsatisfiedLinkError: no CGAL_Kernel in java.library.path: [., /Users/chenhong/git/cgal-swig-bindings/build/CGAL-5.0_release/lib, /Users/chenhong/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2673)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at CGAL.Kernel.CGAL_KernelJNI.<clinit>(CGAL_KernelJNI.java:15)
	at CGAL.Kernel.Point_2.<init>(Point_2.java:60)
	at test_kernel.main(test_kernel.java:19)
(base) chenhong@ChenhonacStudio java % export DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}:/Users/chenhong/git/cgal-swig-bindings/examples/java/lib
(base) chenhong@ChenhonacStudio java % pwd
/Users/chenhong/git/cgal-swig-bindings/examples/java
(base) chenhong@ChenhonacStudio java % echo $DYLD_LIBRARY_PATH
:/Users/chenhong/git/cgal-swig-bindings/build/CGAL-5.0_release/lib:/Users/chenhong/git/cgal-swig-bindings/examples/java/lib
(base) chenhong@ChenhonacStudio java % java test_kernel
poly.size() 3
0 0
0 1
1 1
0 0 0 1
0 1 1 1
1 1 0 0
-0 -0 -0
(base) chenhong@ChenhonacStudio java %

it's ok, thank you very much.

**Comment by sendreams** [comment]
Sorry, i'm not familiar with MacOS, i spend most of my time developing under windows,  i also have compiled this project in windows and succeed, the results file is some of *.dll, i confuse about how to using these dll files in eclipse? can you share me some keyword or idea? thanks

**Comment by lrineau** [comment]
> Sorry, i'm not familiar with MacOS, i spend most of my time developing under windows, i also have compiled this project in windows and succeed, the results file is some of *.dll, i confuse about how to using these dll files in eclipse? can you share me some keyword or idea? thanks

I am sorry. I am not at all familiar with Eclipse. All I know it that the `PATH` environment variable can be used to guide the search of DLL files on Windows.

**Comment by sendreams** [comment]
thanks, i will be trying in some days, if succeed i will post the method here.
