### ISSUE TITLE
Error in "Virtual Memory Allocation"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CGAL/cgal-swig-bindings#43]
```
What steps will reproduce the problem?
1.I follow the steps, including switch the git version to e77c16bd5a65.
2.When I am running > make -j 4, it stops at Mesh_3, and report the error: 
cannot allocate memory.


What is the expected output? What do you see instead?
The expected output is the successful compiling. But My compiling stops at 
Mesh_3


What version of the product are you using? On what operating system?
CGAL version: 3.9
SWIG version: 2.0.4
cmake version: 2.8.7
Java version: 1.6.0-30
Ubuntu version: 12.04

Please provide any additional information below.

```

Original issue reported on code.google.com by `kate.yan...@gmail.com` on 18 Mar 2014 at 6:53

**Comment by echambon** [comment]
Hello, same problem here, crashing at Mesh_3 when trying to build python bindings.
Lubuntu Virtual Machine with 6.9 GB RAM (I noticed using top that the maximum memory was not reached (approx 60%) when crashing). Any hint on how much RAM is required ?
I tried with and without parallel build.

**Comment by lrineau** [comment]
[**@echambon**](https://github.com/echambon) commented on [Nov 13, 2018, 1:13 AM GMT+1](https://github.com/CGAL/cgal-swig-bindings/issues/43#issuecomment-438079284 "2018-11-13T00:13:44Z - Replied by Github Reply Comments"):
> Hello, same problem here, crashing at Mesh_3 when trying to build python bindings.
> Lubuntu Virtual Machine with 6.9 GB RAM (I noticed using top that the maximum memory was not reached (approx 60%) when crashing but probably due to display not showing the effective load). Any hint on how much RAM is required ?
> I tried with and without parallel build.

I can't say for sure, but probably you were compiling a debug version (with the `-g` compiler flags) of the bindings, with a 32 bits version of SWIG, or with a 32 bits version of the compiler. In that case, the 32 bits process is limited to 3GB of virtual memory, and that might be too small to compile Mesh_3 code with debugging information. Was that so?

**Comment by lrineau** [comment]
I confirm: on my 64 bits machine, with a 64 bits compiler, compiling the Mesh_3 bindings with debugging requires 4.2GiB of memory. So, unfortunately, the solution is:
  - either compile in 64 bits,
  - or compile without the debugging symbols.

**Comment by echambon** [comment]
Hello,
Thanks for your answer.
As a matter of fact, I managed to compile successfully by installing a fresh Lubuntu 64 bits virtual machine, so this confirms what you are saying ;-)

Also I had installed Anaconda 3 and I was getting weird warnings when running cmake. Apparently this is not linked however.

Thanks again.
