### ISSUE TITLE
[patches] py3k compatibility

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CGAL/cgal-swig-bindings#45]
```
Hi,

Here are some patches to improve python3 compatibility and some other 
enhancements.

Regards,

J.
```

Original issue reported on code.google.com by `julien.s...@gmail.com` on 9 Apr 2014 at 6:59

Attachments:
* [001-fix-py3-relative-imports.patch](https://storage.googleapis.com/google-code-attachments/cgal-bindings/issue-45/comment-0/001-fix-py3-relative-imports.patch)
* [002-fix-build-ruby-option.patch](https://storage.googleapis.com/google-code-attachments/cgal-bindings/issue-45/comment-0/002-fix-build-ruby-option.patch)
* [003-python-module-version.patch](https://storage.googleapis.com/google-code-attachments/cgal-bindings/issue-45/comment-0/003-python-module-version.patch)
* [004-link-python-option.patch](https://storage.googleapis.com/google-code-attachments/cgal-bindings/issue-45/comment-0/004-link-python-option.patch)
* [005-python-autotests.patch](https://storage.googleapis.com/google-code-attachments/cgal-bindings/issue-45/comment-0/005-python-autotests.patch)
* [006-python3-compatible-tests.patch](https://storage.googleapis.com/google-code-attachments/cgal-bindings/issue-45/comment-0/006-python3-compatible-tests.patch)

**Comment by xantares** [comment]
python 3 support is ok now, to close
