### ISSUE TITLE
cgal-swig-bindings wont compile on Mac

### ISSUE THREAD

**Issue by gphani123** [CGAL/cgal-swig-bindings#65]
When I try to compile the python bindings this is the error message I get

/Users/ghanakot/Software/cgal-swig-bindings-master/SWIG_CGAL/Polygon_mesh_processing/CGAL_Polygon_mesh_processing.i:180: Error: Missing '}'. Reached end of input.
/Users/ghanakot/Software/cgal-swig-bindings-master/SWIG_CGAL/Polygon_mesh_processing/CGAL_Polygon_mesh_processing.i:180: Error: Syntax error in input(1).
make[2]: *** [build-python/CGAL/CGAL_Polygon_mesh_processingPYTHON_wrap.cxx] Error 1
make[1]: *** [SWIG_CGAL/Polygon_mesh_processing/CMakeFiles/_CGAL_Polygon_mesh_processing.dir/all] Error 2
make: *** [all] Error 2

**Comment by sloriot** [comment]
Fixed by be14a415b620743d665020ff37046cc3e02b0f65
