### ISSUE TITLE
Vectorized AABB queries

### ISSUE THREAD

**Issue by Kalkasas** [CGAL/cgal-swig-bindings#68]
I am querying an aabb tree with ~10^6 Point_3 objects at once with python. 
I have to create ~10^6 Point_3 objects and call closest_point_and_primitive multiple times.

My timing tests suggest that a third of the time is spent on just creating the Point_3 objects.

I have no experience with swig. Is there an easy way to support a batch version of the aabb tree queries?

**Comment by sloriot** [comment]
In f1aad36, I've added an overload that allow to call the function with coordinates directly without building a SWIG point type. Let me know if this improves the result significantly.
