### ISSUE TITLE
Bindings in Anaconda Python

### ISSUE THREAD

**Issue by a-jacobo** [CGAL/cgal-swig-bindings#70]
Hi,
   
 Does anyone know how to compile the bindings against Anaconda python in OsX? I've tried installing the bindings from pip but doesn't work, and trying the regular compilation links the bindings against the OsX native python distribution and not Anaconda's. Any help will be appreciated!

Adrian.

**Comment by pwolfram** [comment]
You should try to install via conda: `conda install -c conda-forge cgal=4.8.1`.  I just tested this and a fair number of bindings are available.

**Comment by a-jacobo** [comment]
Thanks! I didn't know that the Conda installation had the bindings too. I thought it was just the libraries.

**Comment by pwolfram** [comment]
@a-jacobo, FYI- I think you can close this issue now because I think your issue has been resolved.

**Comment by jf---** [comment]
I tried installing via python ( admittedly not using a pinned version, but rather `conda install -c conda-forge cgal` ), on osx. On import, I get the following segfault however:

```
In [1]: from CGAL import CGAL_AABB_tree
Fatal Python error: PyThreadState_Get: no current thread
```

Not sure why, the .so file seems correctly linked

In [8]: !otool -L /Users/jelleferinga/miniconda3/envs/generative/lib/python3.6/site-packages/CGAL/_CGAL_Advancing_fron
   ...: t_surface_reconstruction.so
/Users/jelleferinga/miniconda3/envs/generative/lib/python3.6/site-packages/CGAL/_CGAL_Advancing_front_surface_reconstruction.so:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	@rpath/libmpfr.4.dylib (compatibility version 6.0.0, current version 6.5.0)
	@rpath/libgmp.10.dylib (compatibility version 14.0.0, current version 14.2.0)
	@rpath/libCGAL.13.dylib (compatibility version 13.0.0, current version 13.0.1)
	@rpath/libboost_thread.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_system.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_chrono.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_date_time.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_atomic.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libCGAL_Kernel_cpp.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libpython3.6m.dylib (compatibility version 3.6.0, current version 3.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
