### ISSUE TITLE
some iterators don't have a __next__ definition

### ISSUE THREAD

**Issue by lmedioni** [CGAL/cgal-swig-bindings#78]
For instance, this is the case of: 
- Mesh_2_Constrained_Delaunay_triangulation_plus_2_Finite_vertices_iterator
- Mesh_2_Constrained_Delaunay_triangulation_plus_2_Context_iterator
- Mesh_2_Constrained_Delaunay_triangulation_plus_2_Vertices_in_constraint_iterator
- Mesh_2_Constrained_Delaunay_triangulation_plus_2_Finite_edges_iterator
- Mesh_2_Constrained_Delaunay_triangulation_plus_2_Finite_faces_iterator
(CGAL.CGAL_Mesh_2)

When CGAL bindings code is run in Python 3, this leads to that kind of errors :  

> TypeError: iter() returned non-iterator of type 'Mesh_2_Constrained_Delaunay_triangulation_plus_2_Finite_vertices_iterator'

**Comment by sloriot** [comment]
are you using the latest version of the bindings?

**Comment by lmedioni** [comment]
Actually not, because we are still using CGAL 4.3.
But sorry, I hadn't seen [this patch](https://github.com/logilab/cgal-swig-bindings/commit/a14a5b8045da72f4df7ae451fa05e50323f41e91) that solves the problem :).
