### ISSUE TITLE
error compiling on Mac OS 10.11, CGAL 4.7, SWIG 3.0.10, clang 4.2.1, python 2.7.12

### ISSUE THREAD

**Issue by blondegeek** [CGAL/cgal-swig-bindings#83]
Hello,

I seem to have no problems with cmake (cmake output at bottom), but I get the following error when I make:
`1 warning and 5 errors generated.
make[2]: *** [SWIG_CGAL/Advancing_front_surface_reconstruction/CMakeFiles/_CGAL_Advancing_front_surface_reconstruction.dir/__/__/build-python/CGAL/CGAL_Advancing_front_surface_reconstructionPYTHON_wrap.cxx.o] Error 1
make[1]: *** [SWIG_CGAL/Advancing_front_surface_reconstruction/CMakeFiles/_CGAL_Advancing_front_surface_reconstruction.dir/all] Error 2
make: *** [all] Error 2`

As of right now, my clone of cgal-swig-bindings is up-to-date with master.

The following errors are for:
`cgal-swig-bindings/SWIG_CGAL/Advancing_front_surface_reconstruction/impl.h`

`75:17: error: no type named 'Property_map_to_unary_function' in namespace 'CGAL'`
`75:47: error: expected member name or ';' after declaration specifiers`
`76:38: error: use of undeclared identifier 'Unary_function'; did you mean 'std::unary_function'?`
`76:38: error: no template named 'Unary_function'; did you mean 'std::unary_function'?`
`error: use of class template 'unary_function' requires template arguments`

Any idea as to the source of these errors and how to resolve them?
Thanks very much!
Tess

--------------
cmake and flags:
`cmake -DCGAL_DIR=/usr/local/lib/CGAL -DBUILD_PYTHON=ON -DBUILD_JAVA=OFF -DPYTHON_LIBRARIES=/usr/local/lib/python2.7 
-DPYTHON_LIBRARY=/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib -DPython_FRAMEWORKS=/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Headers`

cmake output:

-- Build type: Release
-- USING CXXFLAGS = ' -O3 -DNDEBUG'
-- USING EXEFLAGS = ' -Wl,-dylib_file,/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib:/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib '
-- Targetting Unix Makefiles
-- Using /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ compiler.
-- DARWIN_VERSION=15
-- Mac Leopard detected
-- Requested component: ImageIO
-- Requested component: MPFR
-- Requested component: GMP
-- BUILD_RUBY is set to OFF: no CGAL-bindings for Ruby will be generated.
-- BUILD_JAVA is set to OFF: no CGAL-bindings for Java will be generated.
-- Found Python libs.
-- CGAL-SWIG Python files and libraries will be written in /Users/.../cgal-swig-bindings/build-python/CGAL.
-- Now adding packages
-- Found Eigen3: /usr/local/include/eigen3 (found suitable version "3.2.9", minimum required is "3.1.0") 
-- Found Eigen3: /usr/local/include/eigen3 (found suitable version "3.2.9", minimum required is "3.2.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/.../cgal-swig-bindings

**Comment by lrineau** [comment]
That version of cgal-bindings is probably too recent to be able to compile with CGAL-4.7? Do you have the possibility to upgrade CGAL to CGAL-4.9 and retry?

**Comment by sloriot** [comment]
I just pushed a commit that should fix the issue.

**Comment by blondegeek** [comment]
Thanks for both of your responses! sloriot's fix worked.
