### ISSUE TITLE
Build Failure Triangulation_2

### ISSUE THREAD

**Issue by philzook58** [CGAL/cgal-swig-bindings#84]
I'm using Ubuntu 14.04 with CGAL installed from apt-get

I used
 
cmake -DCGAL_DIR=/usr/lib/CGAL -DBUILD_PYTHON=ON -DBUILD_JAVA=OFF -DJAVA_OUTDIR_PREFIX=../../examples/java ../..

and then ran 
make -j 4

and received the error:

In file included from /home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/all_includes.h:17:0,
                 from /home/philip/Documents/cgal/cgal-swig-bindings/build/CGAL4.9/SWIG_CGAL/Triangulation_2/CGAL_Triangulation_2PYTHON_wrap.cxx:3214:
/home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/Constrained_triangulation_plus_2.h: In instantiation of ‘struct Constraint_id_wrapper<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> > >’:
/home/philip/Documents/cgal/cgal-swig-bindings/build/CGAL4.9/SWIG_CGAL/Triangulation_2/CGAL_Triangulation_2PYTHON_wrap.cxx:100120:42:   required from here
/home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/Constrained_triangulation_plus_2.h:48:45: error: no type named ‘Constraint_id’ in ‘class CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >’
   typedef typename CDTP2_cpp::Constraint_id cpp_base;
                                             ^
In file included from /home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/all_includes.h:17:0,
                 from /home/philip/Documents/cgal/cgal-swig-bindings/build/CGAL4.9/SWIG_CGAL/Triangulation_2/CGAL_Triangulation_2PYTHON_wrap.cxx:3214:
/home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/Constrained_triangulation_plus_2.h: In instantiation of ‘Constraint_id_wrapper<Cpp_base> Constrained_triangulation_plus_2_wrapper<Cpp_base, Base_triangulation_wrapper, Vertex_handle>::insert_constraint(const Polygon_2&) [with Cpp_base = CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >; Base_triangulation_wrapper = Constrained_Delaunay_triangulation_2_wrapper<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >, SWIG_Triangulation_2::CGAL_Vertex_handle<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >, Point_2>, SWIG_Triangulation_2::CGAL_Face_handle<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >, Point_2> >; Vertex_handle = SWIG_Triangulation_2::CGAL_Vertex_handle<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >, Point_2>]’:
/home/philip/Documents/cgal/cgal-swig-bindings/build/CGAL4.9/SWIG_CGAL/Triangulation_2/CGAL_Triangulation_2PYTHON_wrap.cxx:100138:66:   required from here
/home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/Constrained_triangulation_plus_2.h:118:59: error: no matching function for call to ‘CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >::insert_constraint(const cpp_base&)’
     return this->get_data().insert_constraint(p.get_data());
                                                           ^
/home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/Constrained_triangulation_plus_2.h:118:59: note: candidates are:
In file included from /home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/typedefs.h:19:0,
                 from /home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/all_includes.h:11,
                 from /home/philip/Documents/cgal/cgal-swig-bindings/build/CGAL4.9/SWIG_CGAL/Triangulation_2/CGAL_Triangulation_2PYTHON_wrap.cxx:3214:
/usr/include/CGAL/Constrained_triangulation_plus_2.h:376:1: note: void CGAL::Constrained_triangulation_plus_2<Tr>::insert_constraint(const Point&, const Point&) [with Tr = CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag>; CGAL::Constrained_triangulation_plus_2<Tr>::Point = CGAL::Point_2<CGAL::Epick>]
 Constrained_triangulation_plus_2<Tr>::
 ^
/usr/include/CGAL/Constrained_triangulation_plus_2.h:376:1: note:   candidate expects 2 arguments, 1 provided
/usr/include/CGAL/Constrained_triangulation_plus_2.h:390:1: note: void CGAL::Constrained_triangulation_plus_2<Tr>::insert_constraint(CGAL::Constrained_triangulation_plus_2<Tr>::Vertex_handle, CGAL::Constrained_triangulation_plus_2<Tr>::Vertex_handle) [with Tr = CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag>; CGAL::Constrained_triangulation_plus_2<Tr>::Vertex_handle = CGAL::internal::CC_iterator<CGAL::Compact_container<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> > > >, CGAL::Default>, false>]
 Constrained_triangulation_plus_2<Tr>::
 ^
/usr/include/CGAL/Constrained_triangulation_plus_2.h:390:1: note:   candidate expects 2 arguments, 1 provided
In file included from /home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/all_includes.h:17:0,
                 from /home/philip/Documents/cgal/cgal-swig-bindings/build/CGAL4.9/SWIG_CGAL/Triangulation_2/CGAL_Triangulation_2PYTHON_wrap.cxx:3214:
/home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/Constrained_triangulation_plus_2.h: In instantiation of ‘Constraint_id_wrapper<Cpp_base> Constrained_triangulation_plus_2_wrapper<Cpp_base, Base_triangulation_wrapper, Vertex_handle>::insert_constraint(Wrapper_iterator_helper<Point_2>::input, bool) [with Cpp_base = CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >; Base_triangulation_wrapper = Constrained_Delaunay_triangulation_2_wrapper<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >, SWIG_Triangulation_2::CGAL_Vertex_handle<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >, Point_2>, SWIG_Triangulation_2::CGAL_Face_handle<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >, Point_2> >; Vertex_handle = SWIG_Triangulation_2::CGAL_Vertex_handle<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >, Point_2>; Wrapper_iterator_helper<Point_2>::input = std::pair<Input_iterator_wrapper<Point_2, CGAL::Point_2<CGAL::Epick> >, Input_iterator_wrapper<Point_2, CGAL::Point_2<CGAL::Epick> > >]’:
/home/philip/Documents/cgal/cgal-swig-bindings/build/CGAL4.9/SWIG_CGAL/Triangulation_2/CGAL_Triangulation_2PYTHON_wrap.cxx:100193:51:   required from here
/home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/Constrained_triangulation_plus_2.h:124:80: error: no matching function for call to ‘CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >::insert_constraint(Input_iterator_wrapper<Point_2, CGAL::Point_2<CGAL::Epick> >&, Input_iterator_wrapper<Point_2, CGAL::Point_2<CGAL::Epick> >&, bool&)’
     return this->get_data().insert_constraint(input.first, input.second, closed);
                                                                                ^
/home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/Constrained_triangulation_plus_2.h:124:80: note: candidates are:
In file included from /home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/typedefs.h:19:0,
                 from /home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/all_includes.h:11,
                 from /home/philip/Documents/cgal/cgal-swig-bindings/build/CGAL4.9/SWIG_CGAL/Triangulation_2/CGAL_Triangulation_2PYTHON_wrap.cxx:3214:
/usr/include/CGAL/Constrained_triangulation_plus_2.h:376:1: note: void CGAL::Constrained_triangulation_plus_2<Tr>::insert_constraint(const Point&, const Point&) [with Tr = CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag>; CGAL::Constrained_triangulation_plus_2<Tr>::Point = CGAL::Point_2<CGAL::Epick>]
 Constrained_triangulation_plus_2<Tr>::
 ^
/usr/include/CGAL/Constrained_triangulation_plus_2.h:376:1: note:   candidate expects 2 arguments, 3 provided
/usr/include/CGAL/Constrained_triangulation_plus_2.h:390:1: note: void CGAL::Constrained_triangulation_plus_2<Tr>::insert_constraint(CGAL::Constrained_triangulation_plus_2<Tr>::Vertex_handle, CGAL::Constrained_triangulation_plus_2<Tr>::Vertex_handle) [with Tr = CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag>; CGAL::Constrained_triangulation_plus_2<Tr>::Vertex_handle = CGAL::internal::CC_iterator<CGAL::Compact_container<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> > > >, CGAL::Default>, false>]
 Constrained_triangulation_plus_2<Tr>::
 ^
/usr/include/CGAL/Constrained_triangulation_plus_2.h:390:1: note:   candidate expects 2 arguments, 3 provided
In file included from /home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/all_includes.h:17:0,
                 from /home/philip/Documents/cgal/cgal-swig-bindings/build/CGAL4.9/SWIG_CGAL/Triangulation_2/CGAL_Triangulation_2PYTHON_wrap.cxx:3214:
/home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/Constrained_triangulation_plus_2.h: In instantiation of ‘SWIG_CGAL_Iterator<typename Cpp_base::Vertices_in_constraint_iterator, SWIG_Triangulation_2::CGAL_Vertex_handle<Cpp_base, Point_2> > Constrained_triangulation_plus_2_wrapper<Cpp_base, Base_triangulation_wrapper, Vertex_handle>::vertices_in_constraint(Constraint_id_wrapper<Cpp_base>) [with Cpp_base = CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >; Base_triangulation_wrapper = Constrained_Delaunay_triangulation_2_wrapper<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >, SWIG_Triangulation_2::CGAL_Vertex_handle<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >, Point_2>, SWIG_Triangulation_2::CGAL_Face_handle<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >, Point_2> >; Vertex_handle = SWIG_Triangulation_2::CGAL_Vertex_handle<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >, Point_2>; typename Cpp_base::Vertices_in_constraint_iterator = std::_List_iterator<CGAL::internal::CC_iterator<CGAL::Compact_container<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> > > >, CGAL::Default>, false> >]’:
/home/philip/Documents/cgal/cgal-swig-bindings/build/CGAL4.9/SWIG_CGAL/Triangulation_2/CGAL_Triangulation_2PYTHON_wrap.cxx:100365:51:   required from here
/home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/Constrained_triangulation_plus_2.h:132:67: error: ‘struct Constraint_id_wrapper<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> > >’ has no member named ‘get_data’
       this->get_data().vertices_in_constraint_end(cid.get_data()) );
                                                                   ^
/home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/Constrained_triangulation_plus_2.h:132:67: error: ‘struct Constraint_id_wrapper<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> > >’ has no member named ‘get_data’
/home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/Constrained_triangulation_plus_2.h: In instantiation of ‘int Constrained_triangulation_plus_2_wrapper<Cpp_base, Base_triangulation_wrapper, Vertex_handle>::remove_points_without_corresponding_vertex(Constraint_id_wrapper<Cpp_base>) [with Cpp_base = CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >; Base_triangulation_wrapper = Constrained_Delaunay_triangulation_2_wrapper<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >, SWIG_Triangulation_2::CGAL_Vertex_handle<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >, Point_2>, SWIG_Triangulation_2::CGAL_Face_handle<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >, Point_2> >; Vertex_handle = SWIG_Triangulation_2::CGAL_Vertex_handle<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >, Point_2>]’:
/home/philip/Documents/cgal/cgal-swig-bindings/build/CGAL4.9/SWIG_CGAL/Triangulation_2/CGAL_Triangulation_2PYTHON_wrap.cxx:100463:76:   required from here
/home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/Constrained_triangulation_plus_2.h:137:86: error: ‘Triangulation_2_wrapper<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >, Point_2, SWIG_Triangulation_2::CGAL_Vertex_handle<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >, Point_2>, SWIG_Triangulation_2::CGAL_Face_handle<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> >, Point_2>, CGAL::Boolean_tag<false> >::cpp_base’ has no member named ‘remove_points_without_corresponding_vertex’
     return this->get_data().remove_points_without_corresponding_vertex(cid.get_data());
                                                                                      ^
/home/philip/Documents/cgal/cgal-swig-bindings/SWIG_CGAL/Triangulation_2/Constrained_triangulation_plus_2.h:137:86: error: ‘struct Constraint_id_wrapper<CGAL::Constrained_triangulation_plus_2<CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epick, CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_2<void> >, CGAL::Constrained_triangulation_face_base_2<CGAL::Epick> >, CGAL::Exact_predicates_tag> > >’ has no member named ‘get_data’
make[2]: *** [SWIG_CGAL/Triangulation_2/CMakeFiles/_CGAL_Triangulation_2.dir/CGAL_Triangulation_2PYTHON_wrap.cxx.o] Error 1
make[1]: *** [SWIG_CGAL/Triangulation_2/CMakeFiles/_CGAL_Triangulation_2.dir/all] Error 2
make: *** [all] Error 2

Any help would be appreciated.
Thanks.

**Comment by sloriot** [comment]
What version of CGAL are you using?

**Comment by lrineau** [comment]
@philzook58, in https://github.com/CGAL/cgal-swig-bindings/issues/84#issue-206674189 said:
> I'm using Ubuntu 14.04 with CGAL installed from apt-get

@sloriot in https://github.com/CGAL/cgal-swig-bindings/issues/84#issuecomment-278871668 said:
> What version of CGAL are you using?

Ubuntu 14.04 is the version of Ubuntu dated April 2014. But it seems the CGAL package shipped is even older:
https://launchpad.net/ubuntu/trusty/+source/cgal
> cgal source package in Trusty
> [...]
> Current version:    4.2-5ubuntu1
> Uploaded:    2013-12-08

**Comment by lrineau** [comment]
Confirmed by https://www.ubuntuupdates.org/pm/cgal
> trusty | universe | base | 4.2-5ubuntu1

**Comment by lrineau** [comment]
There is a PPA that gives CGAL-4.7 to Trusy:
https://launchpad.net/~nschloe/+archive/ubuntu/cgal-backports
