### ISSUE TITLE
mesh optimization for 2-D meshes

### ISSUE THREAD

**Issue by GabeBalaban** [CGAL/cgal-swig-bindings#88]
Dear Developers,
I would like to use the ODT and or mesh lloyd optimizers on a 2-D mesh I have created. 
In 3-D I see that there exists the functions

CGAL.CGAL_Mesh_3.lloyd_optimize_mesh_3
CGAL.CGAL_Mesh_3.perturb_mesh_3
CGAL.CGAL_Mesh_3.odt_optimize_mesh_3

but I do not see any similar functions for 2-D meshes. Can you please tell me how I can access the 2-D versions of these functions?

**Comment by sloriot** [comment]
The 2D function is recent and has not been added yet. If I'm not too busy tomorrow I'll try doing it

**Comment by GabeBalaban** [comment]
Thanks! Let me know if there is some way I can help.

**Comment by sloriot** [comment]
This should be fixed by a22ccb6d4a307c594ac9bd95d1ac72adea9da5c1 and 9b9bb468bc00be5d2a6c4afeb2843bb0ed6691cd.

**Comment by GabeBalaban** [comment]
Thanks!
