### ISSUE TITLE
Installation For CGAL-SWIG Should Mention Eigen

### ISSUE THREAD

**Issue by NikWillmore** [CGAL/cgal-swig-bindings#90]
Only upon trying CMake-gui for installing CGAL-SWIG do I find I have to discover what Eigen3 is and download it and point CMake-gui to it manually, on Windows 10 with Microsoft Visual Studio Community 2017. Please add Eigen3 mention to this installation manual page:

https://github.com/CGAL/cgal-swig-bindings/wiki/Installation

**Comment by sloriot** [comment]
Done. Note that this is an optional dependency and only some packages will not be built.
