### ISSUE TITLE
Native libraries for all platforms/operating systems

### ISSUE THREAD

**Issue by Pranava29** [CGAL/cgal-swig-bindings#93]
I have built the wrappers in various environments (OSX, Ubuntu) separately and the native libraries generated are in different format (.jnilib for OSX and .so for linux). 

Is there a way to generate the native libraries for all environments in a single step?

**Comment by lrineau** [comment]
No, because you cannot built the OSX library on a Linux. It is not sufficient to name it with the right extension (`.jnilib` or `.so`). The binary code inside is really different.

**Comment by Pranava29** [comment]
okay
