### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by hsmfedor** [CGAL/cgal-swig-bindings#99]
I installed cgal and bindings as follows

> sudo apt-get install libcgal-dev
> pip install cgal-bindings

Then I go the following error

> Python 2.7.12 (default, Dec  4 2017, 14:50:18)
> [GCC 5.4.0 20160609] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> import CGAL.CGAL_Kernel
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/CGAL/CGAL_Kernel.py", line 1568, in <module>
>     ON_NEGATIVE_SIDE = _CGAL_Kernel.ON_NEGATIVE_SIDE
> AttributeError: 'module' object has no attribute 'ON_NEGATIVE_SIDE'

**Comment by lrineau** [comment]
@sciencectn, you are the maintainer of the [pypi package for cgal-bindings][1], do you have a clue?

[1]: https://pypi.org/project/cgal-bindings/

**Comment by sciencectn** [comment]
This is during the pip install right, not while testing it? Can you make it more verbose? 
`pip -v install cgal-bindings`

**Comment by hsmfedor** [comment]
No. It happens when I execute the following in Python

`import CGAL.CGAL_Kernel.`

**Comment by sciencectn** [comment]
From looking at the error you posted, it seems like something went wrong with building the SWIG object files, which start with underscores e.g. `_CGAL_Kernel`. 

If you do `ls` in the installation directory `/usr/local/lib/python2.7/dist-packages/CGAL/`, do you see a `_CGAL_Kernel.so` file?

If not, uninstall it and reinstall it with the verbose option and send me the output.

**Comment by hsmfedor** [comment]
Yes, I have this .so file
https://gyazo.com/3a9abc263cea64a0a1c55f491efb9880

**Comment by hsmfedor** [comment]
I re-installed cgal-bindings with 
`pip -v --no-cache-dir install -U cgal-bindings`

...and now it works!

Something was wrong during installation process apparently.
